<a href="https://colab.research.google.com/github/Gacis/All_Act-Advanced_Pred/blob/main/Untitled3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/shielamae20/Riagacis/main/RailsToTrails_National-Count-Data_week-1.csv')

In [ ]:
df.head()

,Timeframe,Week of,2019 counts (31 counters),2020 counts (31 counters),2021 Counts,Change 2019-2020,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23
0,Week 1,30-Dec,167679.0,183546.0,NaN,9%,1.094627,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Week 2,06-Jan,82340.0,97140.0,NaN,18%,117.974253,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Week 3,13-Jan,62315.0,75782.0,NaN,22%,121.611169,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Week 4,20-Jan,75801.0,83809.0,NaN,11%,110.564504,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Week 5,27-Jan,75841.0,94738.0,NaN,25%,124.916602,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.duplicated().sum()

944

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 53 entries, 0 to 52
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Timeframe                   52 non-null     object
 1   Week of                     52 non-null     object
 2    2019 counts (31 counters)  52 non-null     float64
 3    2020 counts (31 counters)  52 non-null     float64
 4   2021 Counts                 0 non-null      float64
 5   Change 2019-2020            52 non-null     object
 6   Unnamed: 6                  52 non-null     float64
 7   Unnamed: 7                  0 non-null      float64
 8   Unnamed: 8                  1 non-null      object
 9   Unnamed: 9                  1 non-null      float64
 10  Unnamed: 10                 0 non-null      float64
 11  Unnamed: 11                 0 non-null      float64
 12  Unnamed: 12                 0 non-null      float64
 13  Unnamed: 13                 0 non-null      float64
 14  Unnamed: 14                 0 non-null      float64
 15  Unnamed: 15                 0 non-null      float64
 16  Unnamed: 16                 0 non-null      float64
 17  Unnamed: 17                 0 non-null      float64
 18  Unnamed: 18                 0 non-null      float64
 19  Unnamed: 19                 0 non-null      float64
 20  Unnamed: 20                 0 non-null      float64
 21  Unnamed: 21                 0 non-null      float64
 22  Unnamed: 22                 0 non-null      float64
 23  Unnamed: 23                 0 non-null      float64
dtypes: float64(20), object(4)
memory usage: 10.4+ KB

In [ ]:
df['Timeframe'] = pd.to_numeric(df['Timeframe'],errors = 'coerce').astype('Int64')